version: "3.7"
services:
    db:
      image: mysql:8.0.19
      command: '--default-authentication-plugin=mysql_native_password'
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: test
         MYSQL_USER: user
         MYSQL_PASSWORD: 123
      volumes:
         - db_data:/var/lib/mysql
      ports:
         - 3306:3306

    app:
      build: .

    adminer:
      image: adminer
      restart: always
      ports:
         - 8080:8080

volumes:
    db_data: {}
